#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : netcdf
Version  : 4.7.3
Release  : 11
URL      : https://github.com/Unidata/netcdf-c/archive/v4.7.3/netcdf-c-4.7.3.tar.gz
Source0  : https://github.com/Unidata/netcdf-c/archive/v4.7.3/netcdf-c-4.7.3.tar.gz
Summary  : NetCDF Client Library for C
Group    : Development/Tools
License  : BSD-3-Clause
Requires: netcdf-bin = %{version}-%{release}
Requires: netcdf-lib = %{version}-%{release}
Requires: netcdf-license = %{version}-%{release}
Requires: netcdf-man = %{version}-%{release}
Requires: netcdf-openmpi = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : chrpath
BuildRequires : curl-dev
BuildRequires : graphviz
BuildRequires : hdf5-dev
BuildRequires : modules
BuildRequires : openmpi-dev
BuildRequires : openssh
BuildRequires : util-linux
BuildRequires : zlib-dev

%description
The Unidata network Common Data Form (netCDF) is an interface for scientific data access
and a freely-distributed software library that provides an implementation of the interface.
The netCDF library also defines a machine-independent format for representing scientific data.
Together, the interface, library, and format support the creation, access, and sharing of
scientific data. The current netCDF software provides C interfaces for applications and data.

%package bin
Summary: bin components for the netcdf package.
Group: Binaries
Requires: netcdf-license = %{version}-%{release}

%description bin
bin components for the netcdf package.


%package dev
Summary: dev components for the netcdf package.
Group: Development
Requires: netcdf-lib = %{version}-%{release}
Requires: netcdf-bin = %{version}-%{release}
Requires: netcdf-openmpi = %{version}-%{release}
Provides: netcdf-devel = %{version}-%{release}
Requires: netcdf = %{version}-%{release}

%description dev
dev components for the netcdf package.


%package lib
Summary: lib components for the netcdf package.
Group: Libraries
Requires: netcdf-license = %{version}-%{release}

%description lib
lib components for the netcdf package.


%package license
Summary: license components for the netcdf package.
Group: Default

%description license
license components for the netcdf package.


%package man
Summary: man components for the netcdf package.
Group: Default

%description man
man components for the netcdf package.


%package openmpi
Summary: openmpi components for the netcdf package.
Group: Default

%description openmpi
openmpi components for the netcdf package.


%prep
%setup -q -n netcdf-c-4.7.3
cd %{_builddir}/netcdf-c-4.7.3
pushd ..
cp -a netcdf-c-4.7.3 build-openmpi
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585259355
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --enable-shared \
--enable-netcdf-4 \
--enable-dap \
--disable-dap-remote-tests \
--with-pic \
--disable-doxygen
make  %{?_smp_mflags}

pushd ../build-openmpi/
. /usr/share/defaults/etc/profile.d/modules.sh
module load openmpi
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export FCFLAGS="$FCFLAGS -m64 -march=haswell"
export FFLAGS="$FFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
./configure --program-prefix=  --exec-prefix=$MPI_ROOT \
--libdir=$MPI_LIB --bindir=$MPI_BIN --sbindir=$MPI_BIN --includedir=$MPI_INCLUDE \
--datarootdir=$MPI_ROOT/share --mandir=$MPI_MAN -exec-prefix=$MPI_ROOT --sysconfdir=$MPI_SYSCONFIG \
--build=x86_64-generic-linux-gnu --host=x86_64-generic-linux-gnu --target=x86_64-clr-linux-gnu  \
--disable-static --enable-shared \
--enable-netcdf-4 \
--enable-dap \
--disable-dap-remote-tests \
--with-pic \
--disable-doxygen \
--enable-parallel-tests \
--with-mpiexec="mpiexec -x LD_LIBRARY_PATH "
make  %{?_smp_mflags}
module unload openmpi
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build-openmpi;
module load openmpi
export OMPI_MCA_rmaps_base_oversubscribe=1
make VERBOSE=1 V=1 %{?_smp_mflags} check
module unload openmpi

%install
export SOURCE_DATE_EPOCH=1585259355
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/netcdf
cp %{_builddir}/netcdf-c-4.7.3/COPYRIGHT %{buildroot}/usr/share/package-licenses/netcdf/1b45343da188e7ec176d9443c8c3312798532bfc
pushd ../build-openmpi/
module load openmpi
%make_install_openmpi
module unload openmpi
popd
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/libnetcdf.settings

%files bin
%defattr(-,root,root,-)
/usr/bin/nc-config
/usr/bin/nccopy
/usr/bin/ncdump
/usr/bin/ncgen
/usr/bin/ncgen3

%files dev
%defattr(-,root,root,-)
/usr/include/netcdf.h
/usr/include/netcdf_aux.h
/usr/include/netcdf_dispatch.h
/usr/include/netcdf_filter.h
/usr/include/netcdf_mem.h
/usr/include/netcdf_meta.h
/usr/lib64/libh5bzip2.so
/usr/lib64/libnetcdf.so
/usr/lib64/openmpi/include/netcdf.h
/usr/lib64/openmpi/include/netcdf_aux.h
/usr/lib64/openmpi/include/netcdf_dispatch.h
/usr/lib64/openmpi/include/netcdf_filter.h
/usr/lib64/openmpi/include/netcdf_mem.h
/usr/lib64/openmpi/include/netcdf_meta.h
/usr/lib64/openmpi/include/netcdf_par.h
/usr/lib64/openmpi/lib/libh5bzip2.so
/usr/lib64/openmpi/lib/libnetcdf.settings
/usr/lib64/openmpi/lib/libnetcdf.so
/usr/lib64/openmpi/lib/pkgconfig/netcdf.pc
/usr/lib64/pkgconfig/netcdf.pc
/usr/share/man/man3/netcdf.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetcdf.so.15
/usr/lib64/libnetcdf.so.15.2.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netcdf/1b45343da188e7ec176d9443c8c3312798532bfc

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nccopy.1
/usr/share/man/man1/ncdump.1
/usr/share/man/man1/ncgen.1
/usr/share/man/man1/ncgen3.1

%files openmpi
%defattr(-,root,root,-)
/usr/lib64/openmpi/bin/nc-config
/usr/lib64/openmpi/bin/nccopy
/usr/lib64/openmpi/bin/ncdump
/usr/lib64/openmpi/bin/ncgen
/usr/lib64/openmpi/bin/ncgen3
/usr/lib64/openmpi/lib/libnetcdf.so.15
/usr/lib64/openmpi/lib/libnetcdf.so.15.2.1
/usr/lib64/openmpi/share/man/man1/nccopy.1
/usr/lib64/openmpi/share/man/man1/ncdump.1
/usr/lib64/openmpi/share/man/man1/ncgen.1
/usr/lib64/openmpi/share/man/man1/ncgen3.1
/usr/lib64/openmpi/share/man/man3/netcdf.3
