#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : netcdf
Version  : 4.6.1
Release  : 2
URL      : https://github.com/Unidata/netcdf-c/archive/v4.6.1.tar.gz
Source0  : https://github.com/Unidata/netcdf-c/archive/v4.6.1.tar.gz
Summary  : NetCDF Client Library for C
Group    : Development/Tools
License  : NetCDF
Requires: netcdf-bin = %{version}-%{release}
Requires: netcdf-lib = %{version}-%{release}
Requires: netcdf-license = %{version}-%{release}
Requires: netcdf-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : chrpath
BuildRequires : curl-dev
BuildRequires : graphviz
BuildRequires : hdf5-dev
BuildRequires : zlib-dev
Patch1: disable-remote.patch

%description
This directory contains source code for nctest, an extensive test
program for the entire netCDF library.  Before compiling the sources in
this directory, you must have already made the netCDF library from the
../src directory.

%package abi
Summary: abi components for the netcdf package.
Group: Default

%description abi
abi components for the netcdf package.


%package bin
Summary: bin components for the netcdf package.
Group: Binaries
Requires: netcdf-license = %{version}-%{release}
Requires: netcdf-man = %{version}-%{release}

%description bin
bin components for the netcdf package.


%package dev
Summary: dev components for the netcdf package.
Group: Development
Requires: netcdf-lib = %{version}-%{release}
Requires: netcdf-bin = %{version}-%{release}
Provides: netcdf-devel = %{version}-%{release}

%description dev
dev components for the netcdf package.


%package lib
Summary: lib components for the netcdf package.
Group: Libraries
Requires: netcdf-license = %{version}-%{release}

%description lib
lib components for the netcdf package.


%package license
Summary: license components for the netcdf package.
Group: Default

%description license
license components for the netcdf package.


%package man
Summary: man components for the netcdf package.
Group: Default

%description man
man components for the netcdf package.


%prep
%setup -q -n netcdf-c-4.6.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541800952
%configure --disable-static --enable-shared \ \
--enable-netcdf-4 \ \
--enable-dap \ \
--enable-ncgen4 \ \
--enable-extra-example-tests \ \
--disable-dap-remote-tests \ \
--with-pic \ \
--disable-doxygen
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1541800952
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/netcdf
cp COPYRIGHT %{buildroot}/usr/share/package-licenses/netcdf/COPYRIGHT
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/libnetcdf.settings

%files abi
%defattr(-,root,root,-)
/usr/share/abi/libbzip2.so.abi
/usr/share/abi/libmisc.so.abi
/usr/share/abi/libnetcdf.so.13.1.1.abi

%files bin
%defattr(-,root,root,-)
/usr/bin/nc-config
/usr/bin/nccopy
/usr/bin/ncdump
/usr/bin/ncgen
/usr/bin/ncgen3
/usr/bin/ocprint

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libbzip2.so
/usr/lib64/libmisc.so
/usr/lib64/libnetcdf.so
/usr/lib64/pkgconfig/netcdf.pc
/usr/share/man/man3/netcdf.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetcdf.so.13
/usr/lib64/libnetcdf.so.13.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netcdf/COPYRIGHT

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nccopy.1
/usr/share/man/man1/ncdump.1
/usr/share/man/man1/ncgen.1
/usr/share/man/man1/ncgen3.1
